Repository SOPT-all/35-SOPKATHON-ANDROID-ANDROID3, pull requests merged in 2024-11, with the labels that each got.

#5 [SETTING/#3] Typography 기초세팅
  app/src/main/java/com/example/sopkathon_android_team3/ui/theme/Type.kt
  app/src/main/res/font/pretendard_bold.ttf
  app/src/main/res/font/pretendard_regular.ttf
  app/src/main/res/font/pretendard_semibold.ttf
Labels: ⚙️ [SETTING]

#4 [SETTING/#1] Color Scheme 초기 설정
  app/src/main/java/com/example/sopkathon_android_team3/ui/theme/Color.kt
  app/src/main/java/com/example/sopkathon_android_team3/ui/theme/Theme.kt
  app/src/main/java/com/example/sopkathon_android_team3/ui/theme/Type.kt
  app/src/main/res/values/themes.xml
Labels: ⚙️ [SETTING], 🍠 종명

#6 [FEAT/#2] custom dialog component
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sopkathon_android_team3/presentation/component/BasicDialog.kt
  app/src/main/java/com/example/sopkathon_android_team3/presentation/main/MainActivity.kt
Labels: ⭐ [FEAT], 🐈‍⬛ 성민

#10 [FEAT/#8] Main Navigator를 사용한 SAA 적용
  app/build.gradle.kts
  app/src/main/java/com/example/sopkathon_android_team3/presentation/home/HomeScreen.kt
  app/src/main/java/com/example/sopkathon_android_team3/presentation/home/navigation/HomeNavigation.kt
  app/src/main/java/com/example/sopkathon_android_team3/presentation/main/MainActivity.kt
  app/src/main/java/com/example/sopkathon_android_team3/presentation/main/MainScreen.kt
  app/src/main/java/com/example/sopkathon_android_team3/presentation/model/Route.kt
  app/src/main/java/com/example/sopkathon_android_team3/presentation/storage/StorageScreen.kt
  app/src/main/java/com/example/sopkathon_android_team3/presentation/storage/navigation/StorageNavigation.kt
  gradle/libs.versions.toml
Labels: ⭐ [FEAT]

#11 [Feat/#9] component 구현
  app/src/main/java/com/example/sopkathon_android_team3/presentation/component/BasicDialog.kt
  app/src/main/java/com/example/sopkathon_android_team3/presentation/component/DialogTextField.kt
  app/src/main/java/com/example/sopkathon_android_team3/presentation/component/button/ConfirmEvenIfButton.kt
  app/src/main/java/com/example/sopkathon_android_team3/presentation/component/dialog/EvenIfAddDialog.kt
  app/src/main/java/com/example/sopkathon_android_team3/presentation/component/dialog/EvenIfHistoryDialog.kt
Labels: ⭐ [FEAT], 🐈‍⬛ 성민

#15 [Add/#12] 이미지 추가 (큰 수정구 제외)
  app/src/main/res/drawable/btn_write.xml
  app/src/main/res/drawable/ic_arrow_left_gray.xml
  app/src/main/res/drawable/ic_arrow_left_purple.xml
  app/src/main/res/drawable/ic_arrow_right_purple.xml
  app/src/main/res/drawable/ic_close_white.xml
  app/src/main/res/drawable/ic_crystalball_question.xml
  app/src/main/res/drawable/ic_crystalball_small.xml
  app/src/main/res/drawable/ic_storagebox.xml
Labels: ➕ [ADD], 🐈‍⬛ 성민

#17 [SETTING] : main 색상 추가
  app/src/main/java/com/example/sopkathon_android_team3/ui/theme/Color.kt
  app/src/main/java/com/example/sopkathon_android_team3/ui/theme/Type.kt
Labels: ⚙️ [SETTING], 🍠 종명

#18 [FEAT/#14] Home Description Dialog 추가
  app/src/main/java/com/example/sopkathon_android_team3/presentation/home/HomeScreen.kt
  app/src/main/java/com/example/sopkathon_android_team3/presentation/home/component/HomeDescriptionDialog.kt
  app/src/main/res/drawable/img_card_ball.png
  app/src/main/res/values/strings.xml
Labels: ⭐ [FEAT], 🍠 종명

#20 [Feat/#7] lottie component 구현
  app/build.gradle.kts
  app/src/main/java/com/example/sopkathon_android_team3/presentation/component/BasicLottie.kt
  app/src/main/java/com/example/sopkathon_android_team3/presentation/home/HomeScreen.kt
  app/src/main/java/com/example/sopkathon_android_team3/presentation/home/HomeViewModel.kt
  app/src/main/java/com/example/sopkathon_android_team3/presentation/type/CrystalAnimation.kt
  app/src/main/res/raw/p0.lottie
  app/src/main/res/raw/p1.lottie
  app/src/main/res/raw/p2.lottie
  app/src/main/res/raw/p3.lottie
  gradle/libs.versions.toml
Labels: ⭐ [FEAT], 🐯 승범

#24 [FEAT/#21] : API Dto 연결
  app/src/main/java/com/example/sopkathon_android_team3/data/ApiFactory.kt
  app/src/main/java/com/example/sopkathon_android_team3/data/dto/request/RequestBeadContent.kt
  app/src/main/java/com/example/sopkathon_android_team3/data/dto/response/ResponseBeadContent.kt
  app/src/main/java/com/example/sopkathon_android_team3/data/dto/response/ResponseRandomBeadContent.kt
  app/src/main/java/com/example/sopkathon_android_team3/data/service/BeadDataService.kt
Labels: ⭐ [FEAT], 🐯 승범

#22 [Feat/#16] dialog component 구현
  app/src/main/java/com/example/sopkathon_android_team3/presentation/component/DialogTextField.kt
  app/src/main/java/com/example/sopkathon_android_team3/presentation/component/button/ConfirmEvenIfButton.kt
  app/src/main/java/com/example/sopkathon_android_team3/presentation/component/dialog/EvenIfAddDialog.kt
  app/src/main/java/com/example/sopkathon_android_team3/presentation/component/dialog/EvenIfHistoryDialog.kt
Labels: ⭐ [FEAT], 🐈‍⬛ 성민

#30 [FEAT/#29 ] Splash Screen 구현
  app/src/main/java/com/example/sopkathon_android_team3/presentation/main/MainActivity.kt
  app/src/main/java/com/example/sopkathon_android_team3/presentation/splash/SplashScreen.kt
  app/src/main/res/drawable/img_background_no_shadow.png
  app/src/main/res/raw/splash.lottie
  app/src/main/res/values/themes.xml
Labels: ⭐ [FEAT], 🍠 종명

#31 [Feat/#25] navigation server 구현
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/sopkathon_android_team3/data/dto/response/ResponseBeadContent.kt
  app/src/main/java/com/example/sopkathon_android_team3/presentation/component/DialogTextField.kt
  app/src/main/java/com/example/sopkathon_android_team3/presentation/component/dialog/EvenIfAddDialog.kt
  app/src/main/java/com/example/sopkathon_android_team3/presentation/home/HomeScreen.kt
  app/src/main/java/com/example/sopkathon_android_team3/presentation/home/HomeViewModel.kt
  app/src/main/java/com/example/sopkathon_android_team3/presentation/type/CrystalAnimation.kt
  app/src/main/res/raw/p8.lottie
Labels: ⭐ [FEAT], 🐯 승범

#32 [FEAT/#13] Storage UI 구현, Display Screen 서버 통신
  app/src/main/java/com/example/sopkathon_android_team3/data/ApiFactory.kt
  app/src/main/java/com/example/sopkathon_android_team3/data/dto/response/ResponseTotalKingBeadDto.kt
  app/src/main/java/com/example/sopkathon_android_team3/data/service/TotalKingBeadService.kt
  app/src/main/java/com/example/sopkathon_android_team3/presentation/component/dialog/EvenIfHistoryDialog.kt
  app/src/main/java/com/example/sopkathon_android_team3/presentation/component/dialog/HistoryViewModel.kt
  app/src/main/java/com/example/sopkathon_android_team3/presentation/storage/StorageScreen.kt
  app/src/main/java/com/example/sopkathon_android_team3/presentation/storage/StorageViewModel.kt
  app/src/main/res/drawable/ic_king_bead_blue_center.xml
  app/src/main/res/drawable/ic_king_bead_green_center.xml
  app/src/main/res/drawable/ic_king_bead_last.xml
  app/src/main/res/drawable/ic_king_bead_purple_center.xml
Labels: ⭐ [FEAT], 💜 [UI], 💻 서버 통신, 🌻 윤서
